steps:
  - id: "Download dependencies"
    name: golang:1.20.0
    args: ["go", "mod", "download"]
    dir: ./backend
  - id: "Install linting tools"
    name: golang:1.20.0
    args: ["go", "install", "github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2"]
  - id: "Lint"
    name: golang:1.20.0
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        golangci-lint run
    dir: ./backend
  - id: "Run Unit Tests"
    name: golang:1.20.0
    args: ["go", "test", "-v", "./..."]
    dir: ./backend
  - id: "Build Container Image"
    name: "gcr.io/k8s-skaffold/pack"
    entrypoint: pack
    args:
      - build
      - "--builder=gcr.io/buildpacks/builder:v1"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA"
    dir: ./backend
  - id: "Push Container Image"
    name: "gcr.io/cloud-builders/docker:latest"
    args:
      - push
      - "$_GCR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA"
    dir: ./backend
  - id: Deploy to Cloud Run
    name: gcr.io/cloud-builders/gcloud:latest
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        gcloud run deploy ${_SERVICE_NAME} \
          --image $_GCR_HOSTNAME/$PROJECT_ID/$_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA \
          --region ${_DEPLOY_REGION} \
          --no-allow-unauthenticated
    dir: ./backend

substitutions:
  _GCR_HOSTNAME: asia-northeast1-docker.pkg.dev
  _SERVICE_NAME: server
  _DEPLOY_REGION: asia-northeast1
  _REPOSITORY: estock-backend

options:
  volumes:
    - name: go-modules
      path: /go
