// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"context"
	"go.uber.org/zap"
	"net/http"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func initializeServer(ctx context.Context, app *serverApp, handler http.Handler) (*server, func(), error) {
	httpServer := NewHTTPServer(app, handler)
	logger, cleanup, err := SetupLogger()
	if err != nil {
		return nil, nil, err
	}
	cmdServer := &server{
		Server: httpServer,
		logger: logger,
	}
	return cmdServer, func() {
		cleanup()
	}, nil
}

// wire.go:

type server struct {
	*http.Server
	logger *zap.Logger
}
